[Info]
datetime = '13-Dec-2021 11:18:17'
gcodepath = 'testfiles/basics.gcode'
width = '30'
length = '30'
numDefects = '0'

[[printerAction]]
index = 1
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, S4 M5400, I4 M0, R,',
	'F, C, S1 M5400, I1 M-0, R,',
	'F, C, S2 M5400, S3 M5400, I2 M0, I3 M-0, R,',
	'F, C, I2 M-11000, I3 M50000, R,',
]
gcode = 'M200'

[[printerAction]]
index = 2
device = 'Motor'
port = 'COM11'
actions = [
	'F, C, S1 M3000, S2 M3000, I1 M0, I2 M-0, R,',
	'F, C, S1 M3000, S2 M3000, I1 M-1800, I2 M-50000, R,',
]
gcode = 'M200'

[[printerAction]]
index = 3
device = 'Motor'
port = 'COM11'
actions = [
	'F, C, I1 M0, I2 M-0, R,',
]
gcode = 'G01 Z0.0000'

[[printerAction]]
index = 4
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, I1 M0, R,',
	'F, C, I1 M-0, R,',
]
gcode = 'G01 Z0.0000'

[[printerAction]]
index = 5
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, (I2 M0, I3 M0), R,',
]
gcode = 'G01 X0.0000 Y0.0000'

[[printerAction]]
index = 6
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, I2 M12000, R,',
]
gcode = 'G01 X30.0000 Y0.0000'

[[printerAction]]
index = 7
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, I2 M-12000, R,',
]
gcode = 'G01 X0.0000 Y0.0000'

[[printerAction]]
index = 8
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, I3 M12000, R,',
]
gcode = 'G01 X0.0000 Y30.0000'

[[printerAction]]
index = 9
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, I3 M-12000, R,',
]
gcode = 'G01 X0.0000 Y0.0000'

[[printerAction]]
index = 10
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, (I2 M12000, I3 M12000), R,',
]
gcode = 'G01 X30.0000 Y30.0000'

[[printerAction]]
index = 11
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, (I2 M-12000, I3 M-12000), R,',
]
gcode = 'G01 X0.0000 Y0.0000'

[[printerAction]]
index = 12
device = 'Laser'
port = 58176
actions = [
	0x1B,
	0x02,
	0x10,
	0x01,
	0x0D,
	0x3B,
]
gcode = 'M201'

[[printerAction]]
index = 13
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, I2 M12000, R,',
]
gcode = 'G01 X30.0000 Y0.0000'

[[printerAction]]
index = 14
device = 'Laser'
port = 58176
actions = [
	0x1B,
	0x02,
	0x10,
	0x00,
	0x0D,
	0x3A,
]
gcode = 'M202'

[[printerAction]]
index = 15
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, (I2 M-12000, I3 M12000), R,',
]
gcode = 'G01 X0.0000 Y30.0000'

[[printerAction]]
index = 16
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, (I2 M12000, I3 M-12000), R,',
]
gcode = 'G01 X30.0000 Y0.0000'

[[printerAction]]
index = 17
device = 'FuncGen'
port = 'USB::0x0957::0x0407::MY44034072::0::INSTR'
actions = [
	'on'
]
gcode = 'M301'

[[printerAction]]
index = 18
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, I2 M-12000, R,',
]
gcode = 'G01 X0.0000 Y0.0000'

[[printerAction]]
index = 19
device = 'FuncGen'
port = 'USB::0x0957::0x0407::MY44034072::0::INSTR'
actions = [
	'off'
]
gcode = 'M302'

