[Info]
datetime = '02-Dec-2021 01:31:21'
gcodepath = './testFiles/home.gcode'
width = '30'
length = '30'
numDefects = '0'

[[printerAction]]
index = 1
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, S4 M5400, I4 M0, R,',
	'F, C, S1 M5400, I1 M-0, R,',
	'F, C, S2 M5400, S3 M5400, I2 M0, I3 M-0, R,',
	'F, C, I2 M-1800, I3 M13000, R,',
]
gcode = 'M200'

[[printerAction]]
index = 2
device = 'Motor'
port = 'COM11'
actions = [
	'F, C, S1 M3000, S2 M3000, I1 M-1800, I2 M-20000, R,',
]
gcode = 'M200'

