[Info]
datetime = '29-Nov-2021 20:26:08'
gcodepath = './testFiles/small.gcode'
width = '30'
length = '30'
numDefects = '0'

[[printerAction]]
index = 1
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, S4 M5400, I4 M0, R,',
	'F, C, S1 M5400, I1 M-0, R,',
	'F, C, S2 M5400, S3 M5400, I2 M0, I3 M-0, R,',
	'F, C, I2 M-1800, I3 M13000, R,',
]
gcode = '; It calls M200, M201, M202, and G01 commands in all directions.'

[[printerAction]]
index = 2
device = 'Motor'
port = 'COM11'
actions = [
	'F, C, S1 M3000, S2 M3000, I1 M-1800, I2 M-20000, R,',
]
gcode = '; It calls M200, M201, M202, and G01 commands in all directions.'

[[printerAction]]
index = 3
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, S4 M5400, I4 M0, R,',
	'F, C, S1 M5400, I1 M-0, R,',
	'F, C, S2 M5400, S3 M5400, I2 M0, I3 M-0, R,',
	'F, C, I2 M-1800, I3 M13000, R,',
]
gcode = 'M200'

[[printerAction]]
index = 4
device = 'Motor'
port = 'COM11'
actions = [
	'F, C, S1 M3000, S2 M3000, I1 M-1800, I2 M-20000, R,',
]
gcode = 'M200'

[[printerAction]]
index = 5
device = 'Motor'
port = 'COM11'
actions = [
	'F, C, I1 M0, I2 M-0, R,',
]
gcode = 'G01 Z0.0000'

[[printerAction]]
index = 6
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, I1 M0, R,',
	'F, C, I1 M-0, R,',
]
gcode = 'G01 Z0.0000'

[[printerAction]]
index = 7
device = 'Laser'
port = 58176
actions = [
	0x1B,
	0x02,
	0x10,
	0x01,
	0x0D,
	0x3B,
]
gcode = 'M201'

[[printerAction]]
index = 8
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, (I2 M3, I0 M0), R,',
]
gcode = 'G01 X0.0000 Y0.0000'

[[printerAction]]
index = 9
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, I2 M5200, R,',
]
gcode = 'G01 X13.0000 Y0.0000'

[[printerAction]]
index = 10
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, I3 M5200, R,',
]
gcode = 'G01 X13.0000 Y13.0000'

[[printerAction]]
index = 11
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, I2 M-5200, R,',
]
gcode = 'G01 X0.0000 Y13.0000'

[[printerAction]]
index = 12
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, I3 M-5200, R,',
]
gcode = 'G01 X0.0000 Y0.0000'

[[printerAction]]
index = 13
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, (I2 M3, I3950 M1450), R,',
]
gcode = 'G01 X9.8750 Y3.6250'

[[printerAction]]
index = 14
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, I2 M1050, R,',
]
gcode = 'G01 X12.5000 Y3.6250'

[[printerAction]]
index = 15
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, I3 M1050, R,',
]
gcode = 'G01 X12.5000 Y6.2500'

[[printerAction]]
index = 16
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, I2 M-1050, R,',
]
gcode = 'G01 X9.8750 Y6.2500'

[[printerAction]]
index = 17
device = 'Motor'
port = 'COM5'
actions = [
	'F, C, I3 M-1050, R,',
]
gcode = 'G01 X9.8750 Y3.6250'

[[printerAction]]
index = 18
device = 'Laser'
port = 58176
actions = [
	0x1B,
	0x02,
	0x10,
	0x00,
	0x0D,
	0x3A,
]
gcode = 'M202'

